services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/myapp.pfx
    container_name: backend
    image: backend
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      database.server:
        condition: service_healthy

  database.server:
    image: "mcr.microsoft.com/mssql/server"
    container_name: database.server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=TestUser@123
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/data
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "TestUser@123" -Q "SELECT 1" -b -o /dev/null
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
